name: build-artifacts
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies (Linux)
        run: sudo apt-get install libx11-dev libxrandr-dev libxcursor-dev libxi-dev libudev-dev libgl1-mesa-dev
        if: matrix.os == 'ubuntu-latest'

      - uses: lukka/get-cmake@latest

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11.5

      - name: Run CMake and install necessary packages
        uses: lukka/run-cmake@v10.7
        with:
          configurePreset: 'x64-Release'
          buildPreset: 'x64-Release'

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'ubuntu-latest'
        with:
          name: sayaslicer-linux
          path: |
            out/build/x64-Release/sayaslicer/sayaslicer
            out/build/x64-Release/sayaslicer/lang/

      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'windows-latest'
        with:
          name: sayaslicer-windows
          path: |
            out/build/x64-Release/sayaslicer/*.dll
            out/build/x64-Release/sayaslicer/*.exe
            out/build/x64-Release/sayaslicer/lang/

      - name: Upload artifact (macOS x64)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'macos-latest'
        with:
          name: sayaslicer-osx-x64
          path: |
            out/build/x64-Release/sayaslicer/sayaslicer
            out/build/x64-Release/sayaslicer/lang/

      - name: Upload artifact (macOS ARM)
        uses: actions/upload-artifact@v4.3.1
        if: matrix.os == 'macos-14'
        with:
          name: sayaslicer-osx-arm64
          path: |
            out/build/x64-Release/sayaslicer/sayaslicer
            out/build/x64-Release/sayaslicer/lang/
